### ISSUE TITLE
[1.10.2 | 1.11] Mob drops type of kill

### ISSUE THREAD

**Issue by Kashdeya** [TheDragonTeam/MobSettings#2]
Would you be willing to add a config option to make the drops only drop during a player kill? This will help with servers and entities on the ground.

**Comment by sokratis12GR** [comment]
Thanks for the suggestion, I'll look what I can do :)

**Comment by sokratis12GR** [comment]
what would be best. to have 1 option for all mobs or individual for each mob ?
It works:
https://i.gyazo.com/561ccbb2fe2eea2a8ac0011c396fbe08.mp4
Please let me know what would be best:
* keep it like so
* make it for individual mobs
