### ISSUE TITLE
Request - General mob drop! 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TheDragonTeam/MobSettings#3]
So I currently have a currency mod that works only half way. I have ways to sell things but no way to drop things. Could you add a general mob drop function? This would make my life heavenly!

**Comment by sokratis12GR** [comment]
You mean a config entry to add drops to all mobs at once ?

**Comment by P3rf3ctXZer0** [comment]
Yes. It is very critical. Also if you think about future releases of things; a future release of currency type mods with this function would make it so adventure and RPG style servers then always have a currency system.
