### ISSUE TITLE
Crashing when adding mob to biome

### ISSUE THREAD

**Issue by Thyriel** [TheDragonTeam/MobSettings#4]
Version: thedragonlib-1.10.2-1.0.3.1.jar / mobsettings-1.10.2-1.4.1.jar

(still bugged from my comment on curseforge after upgrading lib and mobsettings to the new version)

CrashReport: http://pastebin.com/u13ijV4t
mobsettings.cfg (only blaze added to spawn in a biome): http://pastebin.com/J8d8Cu7J
Instead that 'minecraft:beach' i too tried:
- "minecraft:beach" with ""
- 12 (as it was biomeID before)

Still can't get that thing to work.
Btw as you changed it from biomeID to biome name, where do i find a list of the minecraft:biomenames ? The wiki only has biomeIDs and displaynames, no internal names.

**Comment by sokratis12GR** [comment]
use: minecraft:beach  without anything more

**Comment by sokratis12GR** [comment]
its display names lowercased

**Comment by sokratis12GR** [comment]
I'll try to work on something that will only require you to put the name of the biome

**Comment by Thyriel** [comment]
Ok for ice plains is it then minecraft:iceplains , minecraft:ice_plains or minecraft:ice plains ?
Still crashing btw as seen in the config file above where i tried it with norhing more then minecraft:beach

**Comment by Thyriel** [comment]
Can you maybe try if it's working for you adding blaze to an overworld biome and if yes, give me an example of your config file ?

**Comment by sokratis12GR** [comment]
I wonder if switching back to the legacy builds would be more efficient, I mean switching from registry names over to ids again

**Comment by sokratis12GR** [comment]
I made this just for ease of access to the biome registry names
https://ftb.gamepedia.com/Mob_Settings/Biomes
I hope this helps! :)
